#!/usr/bin/env python

"""
Generate an uniformly distributed array of integers.
"""

import random
import sys

output_path = sys.argv[1];
if len(sys.argv) > 2:
    n = int(sys.argv[2])
else:
    n = 1000;
minv = -2**16
maxv = 2**16 - 1

with open(output_path, 'w') as output_file:
    output_file.write(str(n) + '\n')
    for i in xrange(n - 1):
        output_file.write(str(random.randint(minv, maxv)) + ' ')
    output_file.write(str(random.randint(minv, maxv)) + '\n')
