#!/usr/bin/env python

"""
Generate an uniformly distributed array of integers.
"""

import os.path
import random
import sys

minv = -2**16
maxv = 2**16 - 1

if len(sys.argv) > 1:
    n = int(sys.argv[1])
else:
    n = 1000;

path_base = os.path.basename(__file__)

sum = 0
with open(path_base + '.in', 'w') as f:
    f.write(str(n) + '\n')
    for i in xrange(n - 1):
        r = random.randint(minv, maxv)
        sum += r
        f.write(str(r) + ' ')
    r = random.randint(minv, maxv)
    sum += r
    f.write(str(r) + '\n')

with open(path_base + '.out', 'w') as f:
    f.write(str(sum) + '\n')
